crossover was been installed always

diff --git a/lxc-qvd-ubuntu b/lxc-qvd-ubuntu
--- a/lxc-qvd-ubuntu
+++ b/lxc-qvd-ubuntu
@@ -1027,14 +1027,6 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-if [ -n "crossover" ]; then
-    install_crossover $rootfs
-    if [ "$?" -ne 0 ]; then
-        echo "failed to install crossover"
-        exit 1;
-    fi
-fi
-
 install_qvd_vma "$rootfs" "$qvdmirror" "$qvdversion"
 if [ $? -ne 0 ]; then
     echo "failed to install vma"
@@ -1045,6 +1037,14 @@ install_qvd_desktop $rootfs $desktop
 if [ $? -ne 0 ]; then
     echo "failed to install desktop"
     exit 1
+fi
+
+if [ -n "$crossover" ]; then
+    install_crossover $rootfs
+    if [ "$?" -ne 0 ]; then
+        echo "failed to install crossover"
+        exit 1;
+    fi
 fi
 
 post_process $rootfs $release $trim_container $packages
